# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [14]:
np.__version__, np.show_config()

{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.4",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "lapack": {
      "name"

('2.4.1', None)

#### 3. Create a null vector of size 10 (★☆☆)

In [ ]:
np.zeros(10, 'i8')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4. How to find the memory size of any array (★☆☆)

In [11]:
sample_1 = np.random.randint(1, 100, (5, 5))
print(f'{sample_1.nbytes} Bytes')

200 Bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [15]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out=None``,

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [16]:
sample_2 = np.zeros(10, 'i8')
sample_2[4] = 1
sample_2

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [19]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [18]:
sample_1[::-1]

array([[15, 46, 53,  4, 54],
       [21, 46, 75, 18, 38],
       [76, 56, 82,  3, 75],
       [65, 58, 41,  3, 73],
       [47, 22, 83, 48, 23]])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [20]:
np.arange(0, 9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [21]:
sample_3 = np.array([1, 2, 0, 0, 4, 0])
np.nonzero(sample_3)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [24]:
np.identity(3, 'i8')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [28]:
np.random.randint(1, 100, (3, 3, 3))

array([[[49, 85, 98],
        [ 2, 36, 51],
        [67, 59, 18]],

       [[93, 33, 36],
        [77, 18, 73],
        [73, 50, 50]],

       [[68, 24, 91],
        [12, 42, 53],
        [19,  9, 18]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [30]:
sample_4 = np.random.randint(1, 100, (10, 10))
sample_4.min(), sample_4.min()

(np.int64(2), np.int64(2))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [31]:
sample_5 = np.random.randint(1, 100, 30)
sample_5.mean()

np.float64(50.86666666666667)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [36]:
sample_6 = np.ones((5, 5), dtype='i8')
sample_6[1:-1, 1:-1] = 0
sample_6

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [38]:
np.pad(sample_6, 1)

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 0, 0, 0, 1, 0],
       [0, 1, 1, 1, 1, 1, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
# nan
# False
# False
# nan
# True
# False

0 * np.nan, np.nan == np.nan, np.inf > np.nan, np.nan - np.nan, np.nan in set([np.nan]), 0.3 == 3 * 0.1

(nan, False, False, nan, True, False)

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [42]:
np.diag(1 + np.arange(4), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
np.ones(
    (8, 8),
)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [45]:
sample_7 = np.random.randint(1, 100, (6, 7, 8))
np.unravel_index(99, (6, 7, 8))
sample_7, sample_7[1, 5, 3]

(array([[[71, 20, 88,  6, 99, 72, 62, 56],
         [ 6, 45, 91, 99, 38, 45, 41, 99],
         [12, 63, 34, 26,  7, 12, 84, 13],
         [99,  5, 23, 89, 14, 96, 12, 16],
         [68, 75, 61, 66, 53, 46, 27, 55],
         [96, 68, 39, 31, 46, 21, 39, 35],
         [24, 28,  4,  3, 90, 82, 20, 25]],
 
        [[42, 25, 84, 81, 27, 76, 80,  9],
         [56, 13, 65, 97, 48, 78, 15,  5],
         [96, 81, 50, 99, 64,  3, 63, 14],
         [ 4, 32, 85,  3,  7, 64, 51, 89],
         [10, 95, 93, 37, 57, 77, 42, 71],
         [65, 79, 36, 34, 65, 59, 36, 37],
         [40, 72, 98, 72, 97, 50, 44, 25]],
 
        [[38, 95, 91, 21, 31, 80, 21,  1],
         [70, 83, 92, 60, 43, 53,  5, 69],
         [19, 52, 30, 81, 85, 23, 51,  1],
         [46, 12, 28, 47, 85, 13, 84, 20],
         [35, 10, 96, 36, 59,  1, 51, 20],
         [ 1, 72,  2, 43, 37, 50, 56, 36],
         [49, 97, 42,  3, 21, 78, 49, 75]],
 
        [[34, 67, 68, 33, 74, 48, 25, 61],
         [91, 48, 56, 53, 30, 96, 76, 96],
  

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [14]:
np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [32]:
sample_11 = np.random.random((5, 5))
(sample_11 - np.mean(sample_11)) / (np.std(sample_11))

array([[ 0.09887668,  0.44803204, -1.55341328, -0.70695486, -0.19777213],
       [ 0.90538606,  1.97103808, -0.8846309 , -0.14059427, -0.73033203],
       [-0.19714802, -0.0980807 ,  0.03408574,  2.25557546, -0.53163397],
       [ 0.10091681, -0.75183917, -1.33783043,  0.45679522,  2.26133435],
       [ 0.64083008, -0.54005462,  0.08019787, -0.1879568 , -1.3948272 ]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [35]:
color = np.dtype([('R', np.ubyte), ('G', np.ubyte), ('B', np.ubyte), ('A', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [34]:
sample_12_1 = np.random.randint(1, 100, (5, 3))
sample_12_2 = np.random.randint(1, 100, (3, 2))
sample_12_1 @ sample_12_2

array([[10476,  9485],
       [ 7793,  6758],
       [ 8323,  8022],
       [10485, 10194],
       [ 8808,  7183]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [18]:
sample_13 = np.random.randint(1, 10, (3, 3))
sample_13[(sample_13 > 3) & (sample_13 < 8)] *= -1
sample_13

array([[-4,  1,  8],
       [ 2, -5, -7],
       [-4,  2, -7]])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [23]:
# 9
# imported sum from numpy
# 10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [51]:
sample_16 = np.random.randint(1, 10, (3, 3))
sample_16, sample_16**sample_16, 2 << sample_16 >> 2, 1j * sample_16, sample_16 / 1 / 1

(array([[5, 5, 5],
        [7, 3, 1],
        [4, 2, 5]]),
 array([[  3125,   3125,   3125],
        [823543,     27,      1],
        [   256,      4,   3125]]),
 array([[16, 16, 16],
        [64,  4,  1],
        [ 8,  2, 16]]),
 array([[0.+5.j, 0.+5.j, 0.+5.j],
        [0.+7.j, 0.+3.j, 0.+1.j],
        [0.+4.j, 0.+2.j, 0.+5.j]]),
 array([[5., 5., 5.],
        [7., 3., 1.],
        [4., 2., 5.]]))

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [56]:
np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)

/var/folders/sj/nm63dlv90_1_rgtfjjsgrhf80000gn/T/ipykernel_56156/2446836393.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
/var/folders/sj/nm63dlv90_1_rgtfjjsgrhf80000gn/T/ipykernel_56156/2446836393.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)
/var/folders/sj/nm63dlv90_1_rgtfjjsgrhf80000gn/T/ipykernel_56156/2446836393.py:1: RuntimeWarning: invalid value encountered in cast
  np.array(0) / np.array(0), np.array(0) // np.array(0), np.array([np.nan]).astype(int).astype(float)


(np.float64(nan), np.int64(0), array([0.]))

#### 29. How to round away from zero a float array ? (★☆☆)

In [64]:
sample_17 = np.random.uniform(-10, +10, 10)
sample_17, np.where(sample_17 > 0, np.ceil(sample_17), np.floor(sample_17))

(array([-0.20603808, -5.20577306, -7.37829693,  8.70708168, -0.85760713,
         3.65675404,  5.74547806, -3.24256946, -2.5372949 , -3.47359731]),
 array([-1., -6., -8.,  9., -1.,  4.,  6., -4., -3., -4.]))

#### 30. How to find common values between two arrays? (★☆☆)

In [32]:
sample_14 = np.random.randint(1, 10, 10)
sample_15 = np.random.randint(1, 10, 10)
np.sort(sample_14), np.sort(sample_15), np.intersect1d(sample_14, sample_15)

(array([1, 2, 2, 6, 7, 7, 7, 8, 9, 9]),
 array([1, 1, 2, 2, 3, 3, 4, 7, 8, 9]),
 array([1, 2, 7, 8, 9]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [47]:
# np.seterr(all="ignore")

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [45]:
# False
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/sj/nm63dlv90_1_rgtfjjsgrhf80000gn/T/ipykernel_51921/2429370254.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [44]:
np.datetime64('today') - np.timedelta64(1), np.datetime64('today'), np.datetime64('today') + np.timedelta64(1)

(np.datetime64('2026-01-17'),
 np.datetime64('2026-01-18'),
 np.datetime64('2026-01-19'))

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [53]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [55]:
A = np.random.random((3, 3))
B = np.random.random((3, 3))
np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

array([[-0.55135243, -0.1774101 , -0.01456125],
       [-0.22627054, -0.10934693, -0.11612635],
       [-0.1263886 , -0.44219798, -0.41558476]])

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [38]:
sample_10 = np.random.uniform(0, 10, 10)
sample_10, sample_10.astype('i8'), sample_10 // 1, sample_10 - sample_10 % 1, np.floor(sample_10), np.trunc(sample_10)

(array([0.3514199 , 9.12404588, 8.39707652, 3.05578538, 4.04188541,
        9.13939693, 3.08579869, 0.76131425, 4.53740347, 8.30768143]),
 array([0, 9, 8, 3, 4, 9, 3, 0, 4, 8]),
 array([0., 9., 8., 3., 4., 9., 3., 0., 4., 8.]),
 array([0., 9., 8., 3., 4., 9., 3., 0., 4., 8.]),
 array([0., 9., 8., 3., 4., 9., 3., 0., 4., 8.]),
 array([0., 9., 8., 3., 4., 9., 3., 0., 4., 8.]))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [10]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [20]:
def generate():
    for i in range(10):
        yield i


sample_9 = np.fromiter(generate(), 'i8')
sample_9

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [18]:
np.linspace(0, 1, 11, endpoint=False)[1:]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [4]:
sample_8 = np.random.randint(1, 100, 10)
sample_8, sample_8.sort()

(array([15, 23, 44, 59, 59, 66, 66, 82, 82, 89]), None)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)